// src/lib/components/shared-logins/shared-login-dropdown.svelte
<script lang="ts">
    import * as DropdownMenu from "$lib/components/ui/dropdown-menu";
    import { route } from "$lib/router";
    import {
        decryptAES,
        decryptRSAPassword,
    } from "$lib/util/crypt-utils/cryptography";
    import { mutateSharedLogin } from "$lib/util/mutate-utils/mutate-shared-login";
    import { queryClient } from "$lib/util/query-utils/query-client";
    import { queryLogin } from "$lib/util/query-utils/query-login";
    import { MoreHorizontal } from "@lucide/svelte";
    import { createMutation } from "@tanstack/svelte-query";
    import { toast } from "svelte-sonner";

    const getPasswordSharedByMe = async (id: string) => {
        const { individualLogin } = await queryClient.fetchQuery({
            queryKey: ["individualLogin", id],
            queryFn: ({ signal }) => queryLogin(id, signal),
        });
        return decryptAES(individualLogin.login_password, individualLogin.iv);
    };

    const getPasswordSharedWithMe = async (password: string) => {
        return decryptRSAPassword(password);
    };

    const { login } = $props();
    const byMe = $derived($route.includes("by-me"));
    let dropdownOpen = $state(false);
    const sharedLoginMutation = createMutation({
        mutationKey: ["sharedLogins", "delete"],
        mutationFn: async (loginId: string) => {
            await mutateSharedLogin(null, loginId);
        },
        onError: (error: Error, variables) => {
            toast.error(error.message, {
                description: "Error deleting shared login",
                action: {
                    label: "Try again",
                    onClick: () => $sharedLoginMutation.mutate(variables),
                },
            });
        },
        onSettled: () => {
            queryClient.invalidateQueries({
                queryKey: ["sharedLogins", byMe ? "by_me=true" : ""],
            });
        },
    });
</script>

<DropdownMenu.Root
    open={dropdownOpen}
    onOpenChange={(isOpen) => (dropdownOpen = isOpen)}
>
    <DropdownMenu.Trigger>
        {#snippet child({ props })}
            <MoreHorizontal {...props} />
        {/snippet}
    </DropdownMenu.Trigger>
    <DropdownMenu.Content side="right" align="start">
        <DropdownMenu.Item>
            <button
                onclick={() => navigator.clipboard.writeText(login.login_name)}
            >
                Copy username
            </button>
        </DropdownMenu.Item>
        <DropdownMenu.Item>
            <button
                onclick={async () =>
                    byMe
                        ? navigator.clipboard.writeText(
                              await getPasswordSharedByMe(
                                  login.login_id.toString()
                              )
                          )
                        : navigator.clipboard.writeText(
                              await getPasswordSharedWithMe(
                                  login.login_password
                              )
                          )}
            >
                Copy password
            </button>
        </DropdownMenu.Item>
        {#if login.file}
            <DropdownMenu.Item>
                <a
                    href={"http://127.0.0.1:3000" + login.file}
                    download
                    target="_self"
                >
                    Download file
                </a>
            </DropdownMenu.Item>
        {/if}
        <form
            onsubmit={(event) => {
                event.preventDefault();
                $sharedLoginMutation.mutate(login.id.toString());
            }}
        >
            <button type="submit">
                <DropdownMenu.Item>
                    <span>Delete shared login</span>
                </DropdownMenu.Item>
            </button>
        </form>
    </DropdownMenu.Content>
</DropdownMenu.Root>

// src/lib/components/shared-logins/shared-login-dropdown.tsx
"use client";
import { MoreHorizontal } from "lucide-react";
import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuTrigger,
} from "../ui/dropdown-menu";
import Link from "next/link";
import React, { useState } from "react";
import { queryLogin } from "@/util/query-utils/query-login";
import {
    decryptAES,
    decryptRSAPassword,
} from "@/util/crypt-utils/cryptography";
import { queryClient } from "@/util/query-utils/query-client";
import { useMutation } from "@tanstack/react-query";
import { mutateSharedLogin } from "@/util/mutate-utils/mutate-shared-login";
import { toast } from "sonner";
import { usePathname } from "next/navigation";

const getPasswordSharedByMe = async (id: string) => {
    const { individualLogin } = await queryClient.fetchQuery({
        queryKey: ["individualLogin", id],
        queryFn: ({ signal }) => queryLogin(id, signal),
    });
    return decryptAES(individualLogin.login_password, individualLogin.iv);
};

const getPasswordSharedWithMe = async (password: string) => {
    return decryptRSAPassword(password);
};

type Login = {
    login_name: string;
    login_password: string;
    iv: string;
    file?: string;
    id: number;
    login_id: number;
};

const LoginDropdown: React.FC<{ login: Login }> = (props) => {
    const currentUrl = usePathname();
    const byMe = currentUrl.includes("by-me");
    const [dropdownOpen, setDropdownOpen] = useState(false);
    const sharedLoginMutation = useMutation({
        mutationFn: async (loginId:string) => {
            await mutateSharedLogin(null, loginId);
        },
        mutationKey: ["sharedLogins", "delete"],
        onError: (error: Error) => {
            toast.error(error.message, {
                description: "Error deleting shared login",
                action: {
                    label: "Try again",
                    onClick: () =>
                        sharedLoginMutation.mutate(
                            sharedLoginMutation.variables!
                        ),
                },
            });
        },
        onSettled: () => {
            queryClient.invalidateQueries({
                queryKey: ["sharedLogins", byMe ? "by_me=true" : ""],
            });
        },
    });
    return (
        <DropdownMenu open={dropdownOpen} onOpenChange={setDropdownOpen}>
            <DropdownMenuTrigger asChild>
                <MoreHorizontal />
            </DropdownMenuTrigger>
            <DropdownMenuContent side="right" align="start">
                <DropdownMenuItem>
                    <span
                        onClick={() =>
                            navigator.clipboard.writeText(
                                props.login.login_name
                            )
                        }
                    >
                        Copy username
                    </span>
                </DropdownMenuItem>
                <DropdownMenuItem>
                    <span
                        onClick={async () =>
                            byMe
                                ? navigator.clipboard.writeText(
                                      await getPasswordSharedByMe(
                                          props.login.login_id.toString()
                                      )
                                  )
                                : navigator.clipboard.writeText(
                                      await getPasswordSharedWithMe(
                                          props.login.login_password
                                      )
                                  )
                        }
                    >
                        Copy password
                    </span>
                </DropdownMenuItem>
                {props.login.file ? (
                    <DropdownMenuItem>
                        <Link
                            href={"http://127.0.0.1:3000" + props.login.file}
                            download
                            target="_self"
                        >
                            Download file
                        </Link>
                    </DropdownMenuItem>
                ) : (
                    ""
                )}
                <form
                    onSubmit={(event) => {
                        event.preventDefault();
                        sharedLoginMutation.mutate(props.login.id.toString());
                    }}
                >
                    <button type="submit">
                        <DropdownMenuItem>
                            <span>Delete shared login</span>
                        </DropdownMenuItem>
                    </button>
                </form>
            </DropdownMenuContent>
        </DropdownMenu>
    );
};

export default LoginDropdown;
