// src/lib/components/logins/login-form-inputs.tsx
import { useQuery } from "@tanstack/react-query";
import { Checkbox } from "../ui/checkbox";
import { Input } from "../ui/input";
import { Label } from "../ui/label";
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
} from "../ui/select";
import { Textarea } from "../ui/textarea";
import { queryLogin } from "@/util/query-utils/query-login";
import { decryptAES } from "@/util/crypt-utils/cryptography";
import React, { useEffect, useRef, useState } from "react";
import PasswordGeneratorDialog from "./password-generator-dialog";
import { queryFolders } from "@/util/query-utils/query-folders";
import { Skeleton } from "../ui/skeleton";
import { useParams } from "next/navigation";

type Folder = {
    id: number;
    name: string;
};

const LoginFormInputs: React.FC<{
    isEditable: boolean;
    setValid: (valid: boolean) => void;
}> = (props) => {
    const params = useParams().loginId ?? [];
    const id = [...params].find((param: string) => !isNaN(+param));
    const nameRef = useRef<HTMLInputElement>(null);
    const usernameRef = useRef<HTMLInputElement>(null);
    const urlRef = useRef<HTMLInputElement>(null);
    const [password, setPassword] = useState("");
    function changePassword(password: string) {
        setPassword(password);
    }
    const { data, isFetching } = useQuery({
        queryKey: ["individualLogin", id],
        queryFn: ({ signal }) => {
            return queryLogin(id!, signal);
        },
        enabled: !!id,
    });
    function handleChange() {
        if (
            password &&
            nameRef.current!.value &&
            usernameRef.current!.value &&
            urlRef.current!.value
        ) {
            props.setValid(true);
        } else {
            props.setValid(false);
        }
    }
    const individualLogin = data?.individualLogin ?? null;
    const { data: folders, isFetching: isFetchingFolders } = useQuery({
        queryKey: ["folders"],
        queryFn: ({ signal }) => queryFolders(signal),
    });
    const selectedFolder = individualLogin?.folder_id;
    useEffect(() => {
        const decryptPass = async () => {
            const password = await decryptAES(
                individualLogin?.login_password,
                individualLogin?.iv
            );
            setPassword(password);
            props.setValid(true);
        };
        if (individualLogin) {
            decryptPass();
        }
    }, [individualLogin, props]);

    return (
        <div className="grid gap-4 py-4" onChange={handleChange}>
            <div className="grid grid-cols-4 items-center gap-4">
                <Input type="hidden" name="login[login_id]" value={id ?? ""} />
                <Label htmlFor="name" className="text-right">
                    Name
                </Label>
                {isFetching ? (
                    <Skeleton className="col-span-3 h-8" />
                ) : (
                    <Input
                        id="name"
                        className="col-span-3"
                        name="login[name]"
                        defaultValue={individualLogin?.name}
                        readOnly={!props.isEditable}
                        required
                        ref={nameRef}
                    />
                )}
            </div>
            <div className="grid grid-cols-4 items-center gap-4">
                <Label htmlFor="username" className="text-right">
                    Username
                </Label>
                {isFetching ? (
                    <Skeleton className="col-span-3 h-8" />
                ) : (
                    <Input
                        id="username"
                        className="col-span-3"
                        name="login[login_name]"
                        defaultValue={individualLogin?.login_name}
                        readOnly={!props.isEditable}
                        required
                        ref={usernameRef}
                        autoComplete="off"
                    />
                )}
            </div>
            <div className="grid grid-cols-4 items-center gap-4">
                <Label htmlFor="password" className="text-right">
                    Password
                </Label>
                {isFetching ? (
                    <Skeleton className="col-span-3 h-8" />
                ) : (
                    <Input
                        id="password"
                        type="password"
                        className="col-span-3"
                        name="login[login_password]"
                        readOnly={!props.isEditable}
                        required
                        value={password}
                        onChange={(e) => {
                            setPassword(e.target.value);
                        }}
                        autoComplete="off"
                    />
                )}
            </div>
            <PasswordGeneratorDialog setLoginPassword={changePassword} />
            <div className="grid grid-cols-4 items-center gap-4">
                <Label htmlFor="Url" className="text-right">
                    Url
                </Label>
                <Input
                    type="hidden"
                    name="login[urls_attributes][0][id]"
                    value={individualLogin?.urls[0]?.id || ""}
                />
                {isFetching ? (
                    <Skeleton className="col-span-3 h-8" />
                ) : (
                    <Input
                        id="Url"
                        className="col-span-3"
                        name="login[urls_attributes][0][uri]"
                        defaultValue={individualLogin?.urls[0]?.uri}
                        readOnly={!props.isEditable}
                        required
                        ref={urlRef}
                    />
                )}
            </div>
            <div className="grid grid-cols-4 items-center gap-4">
                <Label htmlFor="notes" className="text-right">
                    Notes
                </Label>
                {isFetching ? (
                    <Skeleton className="col-span-3 h-24" />
                ) : (
                    <Textarea
                        id="notes"
                        className="col-span-3"
                        name="login[notes]"
                        defaultValue={individualLogin?.notes}
                        readOnly={!props.isEditable}
                    />
                )}
            </div>
            <div className="grid grid-cols-4 items-center gap-4">
                <Label htmlFor="custom-field-name" className="text-left">
                    Custom field name
                </Label>
                {isFetching ? (
                    <Skeleton className="col-span-3 h-8" />
                ) : (
                    <Input
                        id="custom-field-name"
                        className="col-span-3"
                        name="login[custom_fields_attributes][0][name]"
                        defaultValue={individualLogin?.custom_fields[0]?.name}
                        readOnly={!props.isEditable}
                    />
                )}
            </div>
            <div className="grid grid-cols-4 items-center gap-4">
                <Label htmlFor="custom-field-value" className="text-left">
                    Custom field value
                </Label>
                <Input
                    type="hidden"
                    name="login[custom_fields_attributes][0][id]"
                    value={individualLogin?.custom_fields[0]?.id}
                />
                {isFetching ? (
                    <Skeleton className="col-span-3 h-8" />
                ) : (
                    <Input
                        id="custom-field-value"
                        className="col-span-3"
                        name="login[custom_fields_attributes][0][value]"
                        defaultValue={individualLogin?.custom_fields[0]?.value}
                        readOnly={!props.isEditable}
                    />
                )}
            </div>
            <div className="grid grid-cols-4 items-center gap-4">
                <Label htmlFor="fav-check" className="text-right">
                    Favorite
                </Label>
                {isFetching ? (
                    <Skeleton className="col-span-3 h-8" />
                ) : (
                    <Checkbox
                        id="fav-check"
                        className="col-span-3"
                        name="login[is_favorite]"
                        defaultChecked={individualLogin?.is_favorite}
                        disabled={!props.isEditable}
                    />
                )}
            </div>
            <div className="grid grid-cols-4 items-center gap-4">
                <Label className="text-right">Folder</Label>
                {isFetchingFolders ? (
                    <Skeleton className="col-span-3 h-8" />
                ) : (
                    <Select
                        name="login[folder_id]"
                        defaultValue={
                            selectedFolder
                                ? selectedFolder.toString()
                                : (folders ?? [])
                                      .find(
                                          (folder: Folder) =>
                                              folder.name === "No folder"
                                      )
                                      ?.id?.toString()
                        }
                        disabled={!props.isEditable}
                    >
                        <SelectTrigger className="w-[295px]">
                            <SelectValue placeholder="Select a folder" />
                        </SelectTrigger>
                        <SelectContent>
                            {(folders ?? []).map((folder: Folder) => (
                                <SelectItem
                                    value={folder.id.toString()}
                                    key={folder.id}
                                >
                                    {folder.name}
                                </SelectItem>
                            ))}
                        </SelectContent>
                    </Select>
                )}
            </div>
            <div className="grid grid-cols-4 items-center gap-4">
                <Label htmlFor="file">File</Label>
                {isFetching ? (
                    <Skeleton className="col-span-3 h-8" />
                ) : (
                    <Input
                        id="file"
                        type="file"
                        className="w-[295px]"
                        name="login[file]"
                        disabled={!props.isEditable}
                    />
                )}
            </div>
        </div>
    );
};
export default LoginFormInputs;

// src/lib/components/logins/login-form-inputs.svelte
<script lang="ts">
    import { route } from "$lib/router";
    import { queryLogin } from "$lib/util/query-utils/query-login";
    import { useQuery } from "@sveltestack/svelte-query";
    import { Skeleton } from "../ui/skeleton";
    import { Input } from "../ui/input";
    import { Label } from "../ui/label";
    import { decryptAES } from "$lib/util/crypt-utils/cryptography";
    import { Textarea } from "../ui/textarea";
    import { Checkbox } from "../ui/checkbox";
    import * as Select from "$lib/components/ui/select/index.js";
    import { queryFolders } from "$lib/util/query-utils/query-folders";
    import PasswordGeneratorDialog from "./password-generator-dialog.svelte";

    type Folder = {
        id: number;
        name: string;
    };

    let { isEditable, setValid } = $props();
    const params = $route.split("/");
    const id = params.find((param) => !isNaN(+param));
    let name = $state("");
    let username = $state("");
    let url = $state("");
    let password = $state("");
    function changePassword(password: string) {
        password = password;
    }
    const loginQuery = useQuery(
        ["individualLogin", id],
        ({ signal }) => {
            return queryLogin(id!, signal);
        },
        {
            enabled: !!id,
        }
    );
    function handleChange() {
        if (password && name && username && url) {
            setValid(true);
        } else {
            setValid(false);
        }
    }
    const individualLogin = $loginQuery?.data?.individualLogin ?? null;
    const folderQuery = useQuery(["folders"], ({ signal }) =>
        queryFolders(signal)
    );
    const selectedFolder = individualLogin?.folder_id;
    $effect(() => {
        const decryptPass = async () => {
            const decryptedPassword = await decryptAES(
                individualLogin?.login_password,
                individualLogin?.iv
            );
            password = decryptedPassword;
            setValid(true);
        };
        if (individualLogin) {
            decryptPass();
        }
    });
    let defaultValue = $state(
        selectedFolder
            ? selectedFolder.toString()
            : ($folderQuery.data ?? [])
                  .find((folder: Folder) => folder.name === "No folder")
                  ?.id?.toString()
    );
</script>

<div class="grid gap-4 py-4" onchange={handleChange}>
    <div class="grid grid-cols-4 items-center gap-4">
        <Input type="hidden" name="login[login_id]" value={id ?? ""} />
        <Label for="name" class="text-right">Name</Label>
        {#if $loginQuery.isFetching}
            <Skeleton class="col-span-3 h-8" />
        {:else}
            <Input
                id="name"
                class="col-span-3"
                name="login[name]"
                defaultValue={individualLogin?.name}
                readonly={!isEditable}
                required
                bind:value={name}
            />
        {/if}
    </div>
    <div class="grid grid-cols-4 items-center gap-4">
        <Label for="username" class="text-right">Username</Label>
        {#if $loginQuery.isFetching}
            <Skeleton class="col-span-3 h-8" />
        {:else}
            <Input
                id="username"
                class="col-span-3"
                name="login[login_name]"
                defaultValue={individualLogin?.login_name}
                readonly={!isEditable}
                required
                bind:value={username}
                autocomplete="off"
            />
        {/if}
    </div>
    <div class="grid grid-cols-4 items-center gap-4">
        <Label for="password" class="text-right">Password</Label>
        {#if $loginQuery.isFetching}
            <Skeleton class="col-span-3 h-8" />
        {:else}
            <Input
                id="password"
                type="password"
                class="col-span-3"
                name="login[login_password]"
                readonly={!isEditable}
                required
                value={password}
                onchange={(e) => {
                    password = (e.target as HTMLInputElement).value;
                }}
                autocomplete="off"
            />
        {/if}
    </div>
    <PasswordGeneratorDialog setLoginPassword={changePassword} />
    <div class="grid grid-cols-4 items-center gap-4">
        <Label for="Url" class="text-right">Url</Label>
        <Input
            type="hidden"
            name="login[urls_attributes][0][id]"
            value={individualLogin?.urls[0]?.id || ""}
        />
        {#if $loginQuery.isFetching}
            <Skeleton class="col-span-3 h-8" />
        {:else}
            <Input
                id="Url"
                class="col-span-3"
                name="login[urls_attributes][0][uri]"
                defaultValue={individualLogin?.urls[0]?.uri}
                readonly={!isEditable}
                required
                bind:value={url}
            />
        {/if}
    </div>
    <div class="grid grid-cols-4 items-center gap-4">
        <Label for="notes" class="text-right">Notes</Label>
        {#if $loginQuery.isFetching}
            <Skeleton class="col-span-3 h-24" />
        {:else}
            <Textarea
                id="notes"
                class="col-span-3"
                name="login[notes]"
                defaultValue={individualLogin?.notes}
                readonly={!isEditable}
            />
        {/if}
    </div>
    <div class="grid grid-cols-4 items-center gap-4">
        <Label for="custom-field-name" class="text-left">
            Custom field name
        </Label>
        {#if $loginQuery.isFetching}
            <Skeleton class="col-span-3 h-8" />
        {:else}
            <Input
                id="custom-field-name"
                class="col-span-3"
                name="login[custom_fields_attributes][0][name]"
                defaultValue={individualLogin?.custom_fields[0]?.name}
                readonly={!isEditable}
            />
        {/if}
    </div>
    <div class="grid grid-cols-4 items-center gap-4">
        <Label for="custom-field-value" class="text-left">
            Custom field value
        </Label>
        <Input
            type="hidden"
            name="login[custom_fields_attributes][0][id]"
            value={individualLogin?.custom_fields[0]?.id}
        />
        {#if $loginQuery.isFetching}
            <Skeleton class="col-span-3 h-8" />
        {:else}
            <Input
                id="custom-field-value"
                class="col-span-3"
                name="login[custom_fields_attributes][0][value]"
                defaultValue={individualLogin?.custom_fields[0]?.value}
                readonly={!isEditable}
            />
        {/if}
    </div>
    <div class="grid grid-cols-4 items-center gap-4">
        <Label for="fav-check" class="text-right">Favorite</Label>
        {#if $loginQuery.isFetching}
            <Skeleton class="col-span-3 h-8" />
        {:else}
            <Checkbox
                id="fav-check"
                class="col-span-3"
                name="login[is_favorite]"
                defaultChecked={individualLogin?.is_favorite}
                disabled={!isEditable}
            />
        {/if}
    </div>
    <div class="grid grid-cols-4 items-center gap-4">
        <Label class="text-right">Folder</Label>
        {#if $folderQuery.isFetching}
            <Skeleton class="col-span-3 h-8" />
        {:else}
            <Select.Root
                name="login[folder_id]"
                value={defaultValue}
                disabled={!isEditable}
            >
                <Select.Trigger class="w-[295px]">
                    Select a folder
                </Select.Trigger>
                <Select.Content>
                    {#each $folderQuery.data ?? [] as folder (folder.id)}
                        <Select.Item value={folder.id.toString()}>
                            {folder.name}
                        </Select.Item>
                    {/each}
                </Select.Content>
            </Select.Root>
        {/if}
    </div>
    <div class="grid grid-cols-4 items-center gap-4">
        <Label for="file">File</Label>
        {#if $loginQuery.isFetching}
            <Skeleton class="col-span-3 h-8" />
        {:else}
            <Input
                id="file"
                type="file"
                class="w-[295px]"
                name="login[file]"
                disabled={!isEditable}
            />
        {/if}
    </div>
</div>
