// src/lib/components/logins/login-dialog.svelte
<script lang="ts">
    import * as Dialog from "$lib/components/ui/dialog/index.js";
    import { navigate, previousPage, route } from "$lib/router";
    import { mutateLogin } from "$lib/util/mutate-utils/mutate-login";
    import { queryClient } from "$lib/util/query-utils/query-client";
    import { toast } from "svelte-sonner";
    import { Button } from "../ui/button";
    import LoginFormInputs from "./login-form-inputs.svelte";
    import { createMutation } from "@tanstack/svelte-query";

    const params = $derived($route.split("/").slice(1));
    const loginId = $derived(params.find((param) => !isNaN(+param.toString())));
    let isNew = $derived($route.includes("new"));
    let isEditable = $derived($route.includes("edit"));
    let dialogOpen = $state(false);
    let valid = $state(false);
    const handleValid = (newValid: boolean) => {
        valid = newValid;
    };
    let loginMutation = createMutation({
        // svelte-ignore state_referenced_locally
        mutationKey: ["login", loginId ? "edit" : "add"],
        mutationFn: async (formData: FormData) => {
            await mutateLogin(formData, loginId, loginId ? "PATCH" : "POST");
        },
        onError: (error: Error, variables) => {
            toast.error(error.message, {
                description: "Failed to save login.",
                action: {
                    label: "Try again",
                    onClick: () => $loginMutation.mutate(variables),
                },
            });
        },
        onSettled: () => {
            queryClient.invalidateQueries({ queryKey: ["logins"] });
        },
    });

    $effect(() => {
        $route;
        dialogOpen = !!loginId || isNew;
        loginMutation = createMutation({
            mutationKey: ["login", loginId ? "edit" : "add"],
            mutationFn: async (formData: FormData) => {
                await mutateLogin(
                    formData,
                    loginId,
                    loginId ? "PATCH" : "POST"
                );
            },
            onError: (error: Error, variables) => {
                toast.error(error.message, {
                    description: "Failed to save login.",
                    action: {
                        label: "Try again",
                        onClick: () => $loginMutation.mutate(variables),
                    },
                });
            },
            onSettled: () => {
                queryClient.invalidateQueries({ queryKey: ["logins"] });
            },
        });
    });
</script>

<Dialog.Root
    open={dialogOpen}
    onOpenChange={(isOpen) => {
        dialogOpen = isOpen;
        if (!isOpen) {
            setTimeout(() => navigate($previousPage), 200);
        }
    }}
>
    <Dialog.Content class="sm:max-w-md">
        <Dialog.Header>
            <Dialog.Title>
                {loginId ? (isEditable ? "Edit" : "View") : "Create"}{" "}
                login
            </Dialog.Title>
        </Dialog.Header>
        <Dialog.Description class="hidden">
            Enter login values
        </Dialog.Description>
        <form
            onsubmit={(e) => {
                e.preventDefault();
                if (valid) {
                    $loginMutation.mutate(
                        new FormData(e.target as HTMLFormElement)
                    );
                    window.history.back();
                }
            }}
            encType="multipart/form-data"
        >
            <LoginFormInputs
                isEditable={isEditable || isNew}
                setValid={handleValid}
            />
            <Dialog.Footer
                class="sm:justify-start"
                hidden={!isEditable && !isNew}
            >
                <Dialog.Close>
                    {#snippet child({ props })}
                        <Button type="button" variant="secondary" {...props}
                            >Close</Button
                        >
                    {/snippet}
                </Dialog.Close>
                <Button type="submit">Save</Button>
            </Dialog.Footer>
        </form>
    </Dialog.Content>
</Dialog.Root>

// src/lib/components/logins/login-dialog.tsx
"use client";
import { Button } from "@/components/ui/button";
import {
    Dialog,
    DialogClose,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
} from "@/components/ui/dialog";
import LoginFormInputs from "./login-form-inputs";
import { useEffect, useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { mutateLogin } from "@/util/mutate-utils/mutate-login";
import { queryClient } from "@/util/query-utils/query-client";
import { toast } from "sonner";
import { useParams, usePathname, useRouter } from "next/navigation";

const LoginDialog = () => {
    const params = useParams().loginId ?? [];
    const loginId = [...params].find((param: string) => !isNaN(+param));
    const [isNew, isEditable] = [
        usePathname().includes("new"),
        usePathname().includes("edit"),
    ];
    const [dialogOpen, setDialogOpen] = useState(false);
    const [valid, setValid] = useState(false);
    const handleValid = (valid: boolean) => {
        setValid(valid);
    };
    useEffect(() => {
        setDialogOpen(!!loginId || isNew);
    }, [loginId, isNew]);
    const navigate = useRouter();
    const loginMutation = useMutation({
        mutationKey: ["login", loginId ? "edit" : "add"],
        mutationFn: async (formData: FormData) => {
            await mutateLogin(formData, loginId, loginId ? "PATCH" : "POST");
        },
        onError: (error: Error, variables) => {
            toast.error(error.message, {
                description: "Failed to save login.",
                action: {
                    label: "Try again",
                    onClick: () => loginMutation.mutate(variables),
                },
            });
        },
        onSettled: () => {
            queryClient.invalidateQueries({ queryKey: ["logins"] });
        },
    });
    return (
        <Dialog
            open={dialogOpen}
            onOpenChange={(isOpen) => {
                setDialogOpen(isOpen);
                if (!isOpen) {
                    setTimeout(() => navigate.back(), 200);
                }
            }}
        >
            <DialogContent className="sm:max-w-md">
                <DialogHeader>
                    <DialogTitle>
                        {loginId ? (isEditable ? "Edit" : "View") : "Create"}{" "}
                        login
                    </DialogTitle>
                </DialogHeader>
                <DialogDescription className="hidden">
                    Enter login values
                </DialogDescription>
                <form
                    onSubmit={(e) => {
                        e.preventDefault();
                        if (valid) {
                            navigate.back();
                            loginMutation.mutate(
                                new FormData(e.target as HTMLFormElement)
                            );
                        }
                    }}
                    encType="multipart/form-data"
                >
                    <LoginFormInputs
                        isEditable={isEditable || isNew}
                        setValid={handleValid}
                    />
                    <DialogFooter
                        className="sm:justify-start"
                        hidden={!isEditable && !isNew}
                    >
                        <DialogClose asChild>
                            <Button type="button" variant="secondary">
                                Close
                            </Button>
                        </DialogClose>
                        <Button>Save</Button>
                    </DialogFooter>
                </form>
            </DialogContent>
        </Dialog>
    );
};

export default LoginDialog;
