// src/lib/components/logins/logins-table.svelte
<script lang="ts">
    import * as Table from "$lib/components/ui/table/index.js";
    import { navigate, route } from "$lib/router";
    import { mutateLogin } from "$lib/util/mutate-utils/mutate-login";
    import { mutateSharedLogin } from "$lib/util/mutate-utils/mutate-shared-login";
    import { queryClient } from "$lib/util/query-utils/query-client";
    import { queryLogins } from "$lib/util/query-utils/query-logins";
    import { toast } from "svelte-sonner";
    import TableContentSkeleton from "../skeletons/table-content-skeleton.svelte";
    import LoginDropdown from "./login-dropdown.svelte";
    import { untrack } from "svelte";
    import {
        createMutation,
        createQuery,
        useMutationState,
    } from "@tanstack/svelte-query";

    type Login = {
        login_id: number;
        name: string;
        login_name: string;
        urls: string[];
        login_password: string;
        iv: string;
    };

    const transformToLogin = (individualFormData: FormData): Login => ({
        login_id: parseInt(
            individualFormData.get("login[login_id]")?.toString() ?? "0"
        ),
        name: individualFormData.get("login[name]")!.toString(),
        login_name: individualFormData.get("login[login_name]")!.toString(),
        urls: [
            individualFormData
                .get("login[urls_attributes][0][uri]")!
                .toString(),
        ],
        login_password: "",
        iv: "",
    });

    const pendingLoginsAdd = useMutationState({
        filters: { mutationKey: ["login", "add"], status: "pending" },
        select: (mutation) =>
            transformToLogin(mutation.state.variables as FormData),
    });
    const pendingLoginsEdit = useMutationState({
        filters: { mutationKey: ["login", "edit"], status: "pending" },
        select: (mutation) =>
            transformToLogin(mutation.state.variables as FormData),
    });
    const pendingLoginsTrash = useMutationState({
        filters: { mutationKey: ["login", "trash"], status: "pending" },
        select: (mutation) => parseInt(mutation.state.variables as string),
    });

    const searchParams = $derived(
        new URLSearchParams($route.split("?")[1] || "")
    );
    let loginsQuery = $state(createQuery<{ logins: Login[] }>({
        // svelte-ignore state_referenced_locally
        queryKey: ["logins", searchParams.toString() || ""],
        queryFn: ({ signal }) =>
            queryLogins(searchParams.toString() || "", signal),
    }));
    const loginMutation = createMutation({
        mutationKey: ["login", "trash"],
        mutationFn: async (loginId: string) => {
            await mutateLogin(null, loginId, "DELETE");
        },
        onError: (error: Error, variables) => {
            console.error(error);
            toast.error(error.message, {
                description: "Error sending login to trash",
                action: {
                    label: "Try again",
                    onClick: () => $loginMutation.mutate(variables),
                },
            });
        },
        onSettled: () => {
            queryClient.invalidateQueries({ queryKey: ["logins", ""] });
        },
    });
    const sharedLoginMutation = createMutation({
        mutationKey: ["sharedLogins", "add"],
        mutationFn: async ({
            formData,
            loginId,
        }: {
            formData: FormData;
            loginId: string;
        }) => {
            navigate("/shared-logins/by-me");
            await mutateSharedLogin(formData, loginId);
        },
        onError: (error: Error, variables) => {
            toast.error(error.message, {
                description: "Error sharing login",
                action: {
                    label: "Try again",
                    onClick: () => $sharedLoginMutation.mutate(variables),
                },
            });
        },
        onSettled: () => {
            queryClient.invalidateQueries({
                queryKey: ["shared-logins", "by_me=true"],
            });
        },
    });
    $effect(() => {
        $route;
        untrack(() => {
            loginsQuery = createQuery({
                queryKey: ["logins", searchParams.toString() || ""],
                queryFn: ({ signal }) =>
                    queryLogins(searchParams.toString() || "", signal),
            });
        });
    });
    $effect(() => {
        if ($loginsQuery.error) {
            toast.error(
                $loginsQuery.error instanceof Error
                    ? $loginsQuery.error.message
                    : "Unknown error",
                {
                    description: "Failed to load logins.",
                    action: {
                        label: "Retry",
                        onClick: () =>
                            queryClient.invalidateQueries({
                                queryKey: [
                                    "logins",
                                    searchParams?.toString() ?? "",
                                ],
                            }),
                    },
                }
            );
        }
    });
</script>

<Table.Root class="table-fixed">
    <Table.Header>
        <Table.Row>
            <Table.Head>Name</Table.Head>
            <Table.Head>Username</Table.Head>
            <Table.Head>URL</Table.Head>
            <Table.Head class="w-16">Actions</Table.Head>
        </Table.Row>
    </Table.Header>
    <Table.Body>
        {#if !$loginsQuery.isSuccess}
            <TableContentSkeleton cellNumber={4} />
        {:else}
            {#each $loginsQuery.data?.logins as login (login.login_id)}
                {@const pendingEdit = $pendingLoginsEdit.find(
                    (pendingLogin) => pendingLogin.login_id === login.login_id
                )}
                {@const pendingTrash = $pendingLoginsTrash.find(
                    (pendingLogin) => pendingLogin === login.login_id
                )}
                <Table.Row
                    class={pendingEdit
                        ? "text-green-500"
                        : pendingTrash
                          ? "text-red-500"
                          : ""}
                >
                    <Table.Cell>
                        <button
                            onclick={() =>
                                navigate("/logins/" + login.login_id + "/edit")}
                            class="w-full text-left"
                        >
                            <div class="w-full">
                                {pendingEdit?.name ?? login.name}
                            </div>
                        </button>
                    </Table.Cell>
                    <Table.Cell>{login.login_name}</Table.Cell>
                    <Table.Cell>
                        <a
                            href={((
                                pendingEdit?.urls[0] ?? login.urls[0]
                            ).includes("http") &&
                                (pendingEdit?.urls[0] ?? login.urls[0])) ||
                                "//" + (pendingEdit?.urls[0] ?? login.urls[0])}
                            target="_blank"
                            rel="noopener noreferrer"
                        >
                            <div class="w-full">
                                {pendingEdit?.urls[0] ?? login.urls[0]}
                            </div>
                        </a>
                    </Table.Cell>
                    <Table.Cell>
                        {#if !pendingEdit && !pendingTrash && login.login_id}
                            <LoginDropdown
                                {login}
                                {loginMutation}
                                {sharedLoginMutation}
                            />
                        {/if}
                    </Table.Cell>
                </Table.Row>
            {/each}
            {#each $pendingLoginsAdd as login, index (index)}
                <Table.Row class="text-gray-500">
                    <Table.Cell>{login.name}</Table.Cell>
                    <Table.Cell>{login.login_name}</Table.Cell>
                    <Table.Cell>{login.urls[0]}</Table.Cell>
                    <Table.Cell />
                </Table.Row>
            {/each}
        {/if}
    </Table.Body>
</Table.Root>

// src/lib/components/logins/logins-table.tsx
"use client";
import { useRouter, useSearchParams } from "next/navigation";
import Link from "next/link";
import LoginDropdown from "./login-dropdown";
import {
    Table,
    TableHeader,
    TableRow,
    TableHead,
    TableBody,
    TableCell,
} from "../ui/table";
import { useEffect } from "react";
import { TableContentSkeleton } from "../skeletons/table-content-skeleton";
import { useMutation, useMutationState, useQuery } from "@tanstack/react-query";
import { queryLogins } from "@/util/query-utils/query-logins";
import { toast } from "sonner";
import { queryClient } from "@/util/query-utils/query-client";
import { mutateLogin } from "@/util/mutate-utils/mutate-login";
import { mutateSharedLogin } from "@/util/mutate-utils/mutate-shared-login";

type Login = {
    login_id: number;
    name: string;
    login_name: string;
    urls: string[];
    login_password: string;
    iv: string;
};

const transformToLogin = (individualFormData: FormData): Login => ({
    login_id: parseInt(
        individualFormData.get("login[login_id]")?.toString() ?? "0"
    ),
    name: individualFormData.get("login[name]")!.toString(),
    login_name: individualFormData.get("login[login_name]")!.toString(),
    urls: [
        individualFormData.get("login[urls_attributes][0][uri]")!.toString(),
    ],
    login_password: "",
    iv: "",
});
function LoginsTable() {
    const searchParams = useSearchParams();
    const { data, error } = useQuery<{ logins: Login[] }>({
        queryKey: ["logins", searchParams?.toString() ?? ""],
        queryFn: ({ signal }) =>
            queryLogins(searchParams?.toString() ?? "", signal),
    });

    useEffect(() => {
        if (error) {
            toast.error(error.message, {
                description: "Failed to load logins.",
                action: {
                    label: "Retry",
                    onClick: () =>
                        queryClient.invalidateQueries({
                            queryKey: [
                                "logins",
                                searchParams?.toString() ?? "",
                            ],
                        }),
                },
            });
        }
    }, [error]);

    const pendingLoginsAdd = useMutationState({
        filters: { mutationKey: ["login", "add"], status: "pending" },
        select: (mutation) =>
            transformToLogin(mutation.state.variables as FormData),
    });
    const pendingLoginsEdit = useMutationState({
        filters: { mutationKey: ["login", "edit"], status: "pending" },
        select: (mutation) =>
            transformToLogin(mutation.state.variables as FormData),
    });
    const pendingLoginsTrash = useMutationState({
        filters: { mutationKey: ["login", "trash"], status: "pending" },
        select: (mutation) => parseInt(mutation.state.variables as string),
    });

    const navigate = useRouter();
    const loginMutation = useMutation({
        mutationFn: async (loginId: string) => {
            await mutateLogin(null, loginId, "DELETE");
        },
        mutationKey: ["login", "trash"],
        onError: (error: Error, variables) => {
            console.error(error);
            toast.error(error.message, {
                description: "Error sending login to trash",
                action: {
                    label: "Try again",
                    onClick: () => loginMutation.mutate(variables),
                },
            });
        },
        onSettled: () => {
            queryClient.invalidateQueries({ queryKey: ["logins", ""] });
        },
    });
    const sharedLoginMutation = useMutation({
        mutationFn: async ({
            formData,
            loginId,
        }: {
            formData: FormData;
            loginId: string;
        }) => {
            navigate.push("/shared-logins/by-me");
            await mutateSharedLogin(formData, loginId);
        },
        mutationKey: ["sharedLogins", "add"],
        onError: (error: Error, variables) => {
            toast.error(error.message, {
                description: "Error sharing login",
                action: {
                    label: "Try again",
                    onClick: () => sharedLoginMutation.mutate(variables),
                },
            });
        },
        onSettled: () => {
            queryClient.invalidateQueries({
                queryKey: ["shared-logins", "by_me=true"],
            });
        },
    });
    return (
        <Table className="table-fixed">
            <TableHeader>
                <TableRow>
                    <TableHead key="name">Name</TableHead>
                    <TableHead key="username">Username</TableHead>
                    <TableHead key="url">URL</TableHead>
                    <TableHead key="actions" className="w-16">
                        Actions
                    </TableHead>
                </TableRow>
            </TableHeader>
            <TableBody>
                {!data?.logins && <TableContentSkeleton cellNumber={4} />}
                {data?.logins?.map((login) => {
                    const pendingEdit = pendingLoginsEdit.find(
                        (pendingLogin) =>
                            pendingLogin.login_id === login.login_id
                    );
                    login = pendingEdit ? pendingEdit : login;
                    const pendingTrash = pendingLoginsTrash.find(
                        (pendingLogin) => pendingLogin === login.login_id
                    );
                    return (
                        <TableRow
                            key={login.login_id.toString()}
                            className={
                                pendingEdit
                                    ? "text-green-500"
                                    : pendingTrash
                                    ? "text-red-500"
                                    : ""
                            }
                        >
                            <TableCell>
                                <Link
                                    href={"/logins/" + login.login_id + "/edit"}
                                >
                                    <div className="w-full">{login.name}</div>
                                </Link>
                            </TableCell>
                            <TableCell>{login.login_name}</TableCell>
                            <TableCell>
                                <Link
                                    href={
                                        (login.urls[0].includes("http") &&
                                            login.urls[0]) ||
                                        "//" + login.urls[0]
                                    }
                                    target="_blank"
                                    rel="noopener noreferrer"
                                >
                                    <div className="w-full">
                                        {login.urls[0]}
                                    </div>
                                </Link>
                            </TableCell>
                            <TableCell>
                                {!pendingEdit && !pendingTrash && (
                                    <LoginDropdown
                                        login={login}
                                        loginMutation={loginMutation}
                                        sharedLoginMutation={
                                            sharedLoginMutation
                                        }
                                    />
                                )}
                            </TableCell>
                        </TableRow>
                    );
                })}
                {pendingLoginsAdd.map((login, index) => (
                    <TableRow
                        key={"pending-add-" + index}
                        className="text-gray-500"
                    >
                        <TableCell>{login.name}</TableCell>
                        <TableCell>{login.login_name}</TableCell>
                        <TableCell>{login.urls[0]}</TableCell>
                        <TableCell />
                    </TableRow>
                ))}
            </TableBody>
        </Table>
    );
}

export default LoginsTable;
