// src/lib/components/logins/login-dropdown.tsx
import { MoreHorizontal } from "lucide-react";
import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuTrigger,
} from "../ui/dropdown-menu";
import Link from "next/link";
import {
    Dialog,
    DialogClose,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
    DialogTrigger,
} from "../ui/dialog";
import React, { useState } from "react";
import { Button } from "../ui/button";
import { Input } from "../ui/input";
import { decryptAES } from "@/util/crypt-utils/cryptography";
import { UseMutationResult } from "@tanstack/react-query";

type Login = {
    login_name: string;
    login_password: string;
    iv: string;
    file?: string;
    login_id: number;
    urls: string[];
};

const LoginDropdown: React.FC<{
    login: Login;
    loginMutation: UseMutationResult<void, Error, string, unknown>;
    sharedLoginMutation: UseMutationResult<
        void,
        Error,
        {
            formData: FormData;
            loginId: string;
        },
        unknown
    >;
}> = (props) => {
    const [dropdownOpen, setDropdownOpen] = useState(false);

    return (
        <DropdownMenu
            modal={false}
            open={dropdownOpen}
            onOpenChange={setDropdownOpen}
        >
            <DropdownMenuTrigger asChild>
                <MoreHorizontal />
            </DropdownMenuTrigger>
            <DropdownMenuContent side="right" align="start">
                <DropdownMenuItem>
                    <span
                        onClick={() =>
                            navigator.clipboard.writeText(
                                props.login.login_name
                            )
                        }
                    >
                        Copy username
                    </span>
                </DropdownMenuItem>
                <DropdownMenuItem>
                    <span
                        onClick={async () =>
                            navigator.clipboard.writeText(
                                await decryptAES(
                                    props.login.login_password,
                                    props.login.iv
                                )
                            )
                        }
                    >
                        Copy password
                    </span>
                </DropdownMenuItem>
                {props.login.file ? (
                    <DropdownMenuItem>
                        <Link
                            href={"http://127.0.0.1:3000" + props.login.file}
                            download
                            target="_self"
                        >
                            Download file
                        </Link>
                    </DropdownMenuItem>
                ) : (
                    ""
                )}
                <DropdownMenuItem asChild>
                    <Link href={"/logins/" + props.login.login_id + "/edit"}>
                        <span>Edit login</span>
                    </Link>
                </DropdownMenuItem>
                <Dialog>
                    <DialogTrigger asChild>
                        <DropdownMenuItem
                            onSelect={(event) => {
                                event.preventDefault();
                            }}
                        >
                            <span>Share login</span>
                        </DropdownMenuItem>
                    </DialogTrigger>
                    <DialogContent>
                        <DialogHeader>
                            <DialogTitle>Share login with:</DialogTitle>
                        </DialogHeader>
                        <DialogDescription className="hidden">
                            Enter email address to share login.
                        </DialogDescription>
                        <form
                            onSubmit={(event) => {
                                event.preventDefault();
                                props.sharedLoginMutation.mutate({
                                    loginId: props.login.login_id.toString(),
                                    formData: new FormData(event.currentTarget),
                                });
                            }}
                        >
                            <Input
                                type="hidden"
                                name="shared_login_datum[name]"
                                value={props.login.login_name}
                            />
                            <Input
                                type="hidden"
                                name="shared_login_datum[login_name]"
                                value={props.login.login_name}
                            />
                            <Input
                                type="hidden"
                                name="shared_login_datum[urls_attributes][0][uri]"
                                value={props.login.urls[0]}
                            />
                            <Input
                                type="text"
                                name="shared_login_datum[email]"
                            />
                            <br />
                            <DialogFooter>
                                <DialogClose asChild>
                                    <Button
                                        type="submit"
                                        onClick={() => {
                                            setDropdownOpen(false);
                                        }}
                                    >
                                        Confirm
                                    </Button>
                                </DialogClose>
                            </DialogFooter>
                        </form>
                    </DialogContent>
                </Dialog>
                <Dialog>
                    <DialogTrigger asChild>
                        <DropdownMenuItem
                            onSelect={(event) => {
                                event.preventDefault();
                            }}
                        >
                            <span>Send to trash</span>
                        </DropdownMenuItem>
                    </DialogTrigger>
                    <DialogContent>
                        <DialogHeader>
                            <DialogTitle>
                                Are you sure you want to send to trash?
                            </DialogTitle>
                        </DialogHeader>
                        <DialogDescription className="hidden">
                            Send login to trash.
                        </DialogDescription>
                        <DialogFooter>
                            <DialogClose asChild>
                                <Button
                                    variant="outline"
                                    onClick={() => {
                                        setDropdownOpen(false);
                                    }}
                                >
                                    No
                                </Button>
                            </DialogClose>
                            <DialogClose asChild>
                                <Button
                                    type="button"
                                    onClick={() => {
                                        props.loginMutation.mutate(
                                            props.login.login_id.toString()
                                        );
                                        setDropdownOpen(false);
                                    }}
                                >
                                    Yes
                                </Button>
                            </DialogClose>
                        </DialogFooter>
                    </DialogContent>
                </Dialog>
            </DropdownMenuContent>
        </DropdownMenu>
    );
};

export default LoginDropdown;

// src/lib/components/logins/login-dropdown.svelte
<script lang="ts">
    import * as DropdownMenu from "$lib/components/ui/dropdown-menu/index.js";
    import * as Dialog from "$lib/components/ui/dialog/index.js";
    import { MoreHorizontal } from "@lucide/svelte";
    import { decryptAES } from "$lib/util/crypt-utils/cryptography";
    import { navigate } from "$lib/router";
    import { Input } from "../ui/input";
    import { Button } from "../ui/button";
    
    const { login, loginMutation, sharedLoginMutation } = $props();
    let dropdownOpen = $state(false);
</script>

<DropdownMenu.Root
    open={dropdownOpen}
    onOpenChange={() => (dropdownOpen = !dropdownOpen)}
>
    <DropdownMenu.Trigger>
        {#snippet child({ props })}
            <MoreHorizontal {...props} />
        {/snippet}
    </DropdownMenu.Trigger>
    <DropdownMenu.Content side="right" align="start">
        <DropdownMenu.Item>
            <button
                onclick={() => navigator.clipboard.writeText(login.login_name)}
            >
                Copy username
            </button>
        </DropdownMenu.Item>
        <DropdownMenu.Item>
            <button
                onclick={async () =>
                    navigator.clipboard.writeText(
                        await decryptAES(login.login_password, login.iv)
                    )}
            >
                Copy password
            </button>
        </DropdownMenu.Item>
        {#if login.file}
            <DropdownMenu.Item>
                <a
                    href={"http://127.0.0.1:3000" + login.file}
                    download
                    target="_self"
                >
                    Download file
                </a>
            </DropdownMenu.Item>
        {/if}
        <DropdownMenu.Item>
            {#snippet child({ props })}
                <button
                    onclick={() =>
                        navigate("/logins/" + login.login_id + "/edit")}
                    {...props}
                >
                    <span>Edit login</span>
                </button>
            {/snippet}
        </DropdownMenu.Item>
        <Dialog.Root>
            <Dialog.Trigger>
                {#snippet child({ props })}
                    <DropdownMenu.Item
                        onSelect={(event) => {
                            event.preventDefault();
                        }}
                        {...props}
                    >
                        <span>Share login</span>
                    </DropdownMenu.Item>
                {/snippet}
            </Dialog.Trigger>
            <Dialog.Content>
                <Dialog.Header>
                    <Dialog.Title>Share login with:</Dialog.Title>
                </Dialog.Header>
                <Dialog.Description class="hidden">
                    Enter email address to share login.
                </Dialog.Description>
                <form
                    onsubmit={(event) => {
                        event.preventDefault();
                        sharedLoginMutation.mutate({
                            loginId: login.login_id.toString(),
                            formData: new FormData(event.currentTarget),
                        });
                    }}
                >
                    <Input
                        type="hidden"
                        name="shared_login_datum[name]"
                        value={login.login_name}
                    />
                    <Input
                        type="hidden"
                        name="shared_login_datum[login_name]"
                        value={login.login_name}
                    />
                    <Input
                        type="hidden"
                        name="shared_login_datum[urls_attributes][0][uri]"
                        value={login.urls[0]}
                    />
                    <Input type="text" name="shared_login_datum[email]" />
                    <br />
                    <Dialog.Footer>
                        <Dialog.Close>
                            {#snippet child({ props })}
                                <Button
                                    type="submit"
                                    onclick={() => {
                                        dropdownOpen = false;
                                    }}
                                >
                                    Confirm
                                </Button>
                            {/snippet}
                        </Dialog.Close>
                    </Dialog.Footer>
                </form>
            </Dialog.Content>
        </Dialog.Root>
        <Dialog.Root>
            <Dialog.Trigger>
                {#snippet child({ props })}
                    <DropdownMenu.Item
                        onSelect={(event) => {
                            event.preventDefault();
                        }}
                        {...props}
                    >
                        <span>Send to trash</span>
                    </DropdownMenu.Item>
                {/snippet}
            </Dialog.Trigger>
            <Dialog.Content>
                <Dialog.Header>
                    <Dialog.Title>
                        Are you sure you want to send to trash?
                    </Dialog.Title>
                </Dialog.Header>
                <Dialog.Description class="hidden">
                    Send login to trash.
                </Dialog.Description>
                <Dialog.Footer>
                    <Dialog.Close>
                        {#snippet child({ props })}
                            <Button
                                variant="outline"
                                onclick={() => {
                                    dropdownOpen = false;
                                }}
                                {...props}
                            >
                                No
                            </Button>
                        {/snippet}
                    </Dialog.Close>
                    <Dialog.Close>
                        {#snippet child({ props })}
                            <Button
                                type="button"
                                onclick={() => {
                                    loginMutation.mutate(
                                        login.login_id.toString()
                                    );
                                    dropdownOpen = false;
                                }}
                                {...props}
                            >
                                Yes
                            </Button>
                        {/snippet}
                    </Dialog.Close>
                </Dialog.Footer>
            </Dialog.Content>
        </Dialog.Root>
    </DropdownMenu.Content>
</DropdownMenu.Root>
