// src/lib/components/ssh-keys/ssh-key-form-inputs.svelte
<script lang="ts">
    import { route } from "$lib/router";
    import { decryptAES } from "$lib/util/crypt-utils/cryptography";
    import { querySSHKey } from "$lib/util/query-utils/query-ssh-key";
    import { generateKeyPair } from "web-ssh-keygen";
    import { Label } from "../ui/label";
    import { Skeleton } from "../ui/skeleton";
    import { Input } from "../ui/input";
    import { Button } from "../ui/button";
    import { Textarea } from "../ui/textarea";
    import { untrack } from "svelte";
    import { createQuery } from "@tanstack/svelte-query";

    const params = $route.split("/").slice(1);
    const id = params.find((param) => !isNaN(+param));
    let privateKey = $state("");
    let publicKey = $state("");
    let name = $state("");
    let notes = $state("");
    let privateKeyMasked = $state(true);
    const individualSSHKeyQuery = createQuery({
        queryKey: ["individualSSHKey", id],
        queryFn: ({ signal }) => querySSHKey(id!, signal),
        enabled: !!id,
    });
    let individualSSHKey = $state({
        name: "",
        private_key: "",
        public_key: "",
        notes: "",
        iv: "",
    });
    $effect(() => {
        $individualSSHKeyQuery.isSuccess;
        untrack(() => {
            const decryptPass = async () => {
                individualSSHKey =
                    $individualSSHKeyQuery.data!.individualSSHKey;
                const decryptedPrivateKey = await decryptAES(
                    individualSSHKey?.private_key,
                    individualSSHKey?.iv
                );
                privateKey = decryptedPrivateKey;
                publicKey = individualSSHKey.public_key;
                name = individualSSHKey?.name;
                notes = individualSSHKey?.notes;
            };
            if ($individualSSHKeyQuery.isSuccess) decryptPass();
        });
    });
    $effect(() => {
        async function generateSSHKey() {
            const {
                privateKey: generatedPrivateKey,
                publicKey: generatedPublicKey,
            } = await generateKeyPair({
                alg: "RSASSA-PKCS1-v1_5",
                size: 2048,
                hash: "SHA-256",
                name: "ssh-key",
            });

            privateKey = generatedPrivateKey;
            publicKey = generatedPublicKey;
        }

        if (!id) generateSSHKey();
    });
</script>

<div class="grid gap-4 py-4">
    <div class="grid grid-cols-4 items-center gap-4">
        <Label for="name" class="text-right">Name</Label>
        {#if $individualSSHKeyQuery.isFetching}
            <Skeleton class="col-span-3 h-8" />
        {:else}
            <Input
                id="name"
                class="col-span-3"
                name="sshkey[name]"
                bind:value={name}
            />
        {/if}
    </div>
    <div class="grid grid-cols-4 items-center gap-4">
        <Label
            for="private-key"
            class="flex flex-col items-start text-left mb-auto"
        >
            Private key
            <div>
                <Button
                    variant={"ghost"}
                    type="button"
                    onclick={() => (privateKeyMasked = !privateKeyMasked)}
                    class="h-5 w-5"
                >
                    <i class="fas fa-eye"></i>
                </Button>
                <Button
                    variant={"ghost"}
                    type="button"
                    onclick={() => navigator.clipboard.writeText(privateKey)}
                    class="h-5 w-5"
                >
                    <i class="fas fa-clipboard"></i>
                </Button>
            </div>
        </Label>
        {#if $individualSSHKeyQuery.isFetching}
            <Skeleton class="col-span-3 h-30" hidden={!privateKeyMasked} />
        {:else}
            <Textarea
                id="private-key"
                class="col-span-3 h-30"
                readonly={true}
                value={"•".repeat(privateKey.length)}
                hidden={!privateKeyMasked}
            />
        {/if}
        {#if $individualSSHKeyQuery.isFetching}
            <Skeleton class="col-span-3 h-30" hidden={privateKeyMasked} />
        {:else}
            <Textarea
                id="private-key"
                class="col-span-3 h-30"
                name="sshkey[private_key]"
                readonly={true}
                value={privateKey}
                hidden={privateKeyMasked}
            />
        {/if}
    </div>
    <div class="grid grid-cols-4 items-center gap-4">
        <Label
            for="public-key"
            class="flex flex-col items-start text-right mb-auto"
        >
            Public key
            <Button
                variant={"ghost"}
                type="button"
                onclick={() => navigator.clipboard.writeText(publicKey)}
                class="h-5 w-5"
            >
                <i class="fas fa-clipboard"></i>
            </Button>
        </Label>
        {#if $individualSSHKeyQuery.isFetching}
            <Skeleton class="col-span-3 h-30" />
        {:else}
            <Textarea
                id="public-key"
                class="col-span-3 h-30"
                name="sshkey[public_key]"
                readonly={true}
                value={publicKey}
            />
        {/if}
    </div>
    <div class="grid grid-cols-4 items-center gap-4">
        <Label for="notes" class="text-right mb-auto">Notes</Label>
        {#if $individualSSHKeyQuery.isFetching}
            <Skeleton class="col-span-3 h-15" />
        {:else}
            <Textarea
                id="notes"
                class="col-span-3"
                name="sshkey[notes]"
                bind:value={notes}
            />
        {/if}
    </div>
</div>

// src/lib/components/ssh-keys/ssh-key-form-inputs.tsx
import { useQuery } from "@tanstack/react-query";
import { Input } from "../ui/input";
import { Label } from "../ui/label";
import { Textarea } from "../ui/textarea";
import { useParams } from "next/navigation";
import { decryptAES } from "@/util/crypt-utils/cryptography";
import { useEffect, useState } from "react";
import { generateKeyPair } from "web-ssh-keygen";
import { querySSHKey } from "@/util/query-utils/query-ssh-key";
import { Button } from "../ui/button";
import { Skeleton } from "../ui/skeleton";

function SSHKeyFormInputs() {
    const params = useParams().sshKeyId || [];
    const id = !isNaN(Number(params[0])) ? params[0] : "";
    const [privateKey, setPrivateKey] = useState("");
    const [publicKey, setPublicKey] = useState("");
    const [privateKeyMasked, setPrivateKeyMasked] = useState(true);
    const { data, isFetching } = useQuery({
        queryKey: ["individualSSHKey", id],
        queryFn: ({ signal }) => querySSHKey(id!, signal),
        enabled: !!id,
    });
    const individualSSHKey = data?.individualSSHKey;
    useEffect(() => {
        const decryptPass = async () => {
            const privateKey = await decryptAES(
                individualSSHKey?.private_key,
                individualSSHKey?.iv
            );
            setPrivateKey(privateKey);
            setPublicKey(individualSSHKey?.public_key);
        };
        if (data) decryptPass();
    }, [data]);
    useEffect(() => {
        async function generateSSHKey() {
            const { privateKey, publicKey } = await generateKeyPair({
                alg: "RSASSA-PKCS1-v1_5",
                size: 2048,
                hash: "SHA-256",
                name: "ssh-key",
            });

            setPrivateKey(privateKey);
            setPublicKey(publicKey);
        }

        if (!id) generateSSHKey();
    }, []);
    return (
        <div className="grid gap-4 py-4">
            <div className="grid grid-cols-4 items-center gap-4">
                <Label htmlFor="name" className="text-right">
                    Name
                </Label>
                {isFetching ? (
                    <Skeleton className="col-span-3 h-8" />
                ) : (
                    <Input
                        id="name"
                        className="col-span-3"
                        name="sshkey[name]"
                        defaultValue={individualSSHKey?.name}
                    />
                )}
            </div>
            <div className="grid grid-cols-4 items-center gap-4">
                <Label
                    htmlFor="private-key"
                    className="flex flex-col items-start text-left mb-auto"
                >
                    Private key
                    <div>
                        <Button
                            variant={"ghost"}
                            type="button"
                            onClick={() =>
                                setPrivateKeyMasked(
                                    (privateKeyMasked) => !privateKeyMasked
                                )
                            }
                            className="h-5 w-5"
                        >
                            <i className="fas fa-eye" />
                        </Button>
                        <Button
                            variant={"ghost"}
                            type="button"
                            onClick={() =>
                                navigator.clipboard.writeText(privateKey)
                            }
                            className="h-5 w-5"
                        >
                            <i className="fas fa-clipboard" />
                        </Button>
                    </div>
                </Label>
                {isFetching ? (
                    <Skeleton
                        className="col-span-3 h-30"
                        hidden={!privateKeyMasked}
                    />
                ) : (
                    <Textarea
                        id="private-key"
                        className="col-span-3 h-30"
                        name="sshkey[private_key]"
                        readOnly={true}
                        value={"•".repeat(privateKey.length)}
                        hidden={!privateKeyMasked}
                    />
                )}
                {isFetching ? (
                    <Skeleton
                        className="col-span-3 h-30"
                        hidden={privateKeyMasked}
                    />
                ) : (
                    <Textarea
                        id="private-key"
                        className="col-span-3 h-30 "
                        name="sshkey[private_key]"
                        readOnly={true}
                        value={privateKey}
                        hidden={privateKeyMasked}
                    />
                )}
            </div>
            <div className="grid grid-cols-4 items-center gap-4">
                <Label
                    htmlFor="public-key"
                    className="flex flex-col items-start text-right mb-auto"
                >
                    Public key
                    <Button
                        variant={"ghost"}
                        type="button"
                        onClick={() => navigator.clipboard.writeText(publicKey)}
                        className="h-5 w-5"
                    >
                        <i className="fas fa-clipboard" />
                    </Button>
                </Label>
                {isFetching ? (
                    <Skeleton className="col-span-3 h-30" />
                ) : (
                    <Textarea
                        id="public-key"
                        className="col-span-3 h-30"
                        name="sshkey[public_key]"
                        readOnly={true}
                        value={publicKey}
                    />
                )}
            </div>
            <div className="grid grid-cols-4 items-center gap-4">
                <Label htmlFor="notes" className="text-right mb-auto">
                    Notes
                </Label>
                {isFetching ? (
                    <Skeleton className="col-span-3 h-15" />
                ) : (
                    <Textarea
                        id="notes"
                        className="col-span-3"
                        name="sshkey[notes]"
                        defaultValue={individualSSHKey?.notes}
                    />
                )}
            </div>
        </div>
    );
}
export default SSHKeyFormInputs;
