// src/lib/components/notes/notes-dialog.tsx
"use client";
import { Button } from "@/components/ui/button";
import {
    Dialog,
    DialogClose,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
} from "@/components/ui/dialog";
import { usePathname, useParams, useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import NotesFormInputs from "./notes-form-inputs";
import { useMutation } from "@tanstack/react-query";
import { mutateNote } from "@/util/mutate-utils/mutate-note";
import { queryClient } from "@/util/query-utils/query-client";
import { toast } from "sonner";

function NotesDialog() {
    const params = useParams().noteId ?? [];
    const noteId = !isNaN(Number(params[0])) ? params[0] : undefined;
    const isNew = usePathname().includes("new");
    const [dialogOpen, setDialogOpen] = useState(false);
    useEffect(() => {
        setDialogOpen(noteId !== undefined || isNew);
    }, [noteId, isNew]);
    const navigate = useRouter();
    const noteMutation = useMutation({
        mutationFn: async (event: React.FormEvent<HTMLFormElement>) => {
            event.preventDefault();
            const formData = new FormData(event.target as HTMLFormElement);
            await mutateNote(formData, noteId, noteId ? "PATCH" : "POST");
        },
        mutationKey: ["note", noteId ? "edit" : "add"],
        onError: (error: Error) => {
            toast.error(error.message, {
                description: "Error saving note",
                action: {
                    label: "Try again",
                    onClick: () => noteMutation.mutate(noteMutation.variables!),
                },
            });
        },
        onSettled: () => {
            queryClient.invalidateQueries({ queryKey: ["notes"] });
        },
    });
    return (
        <Dialog
            open={dialogOpen}
            onOpenChange={(isOpen) => {
                setDialogOpen(isOpen);
                if (!isOpen) {
                    setTimeout(() => navigate.back(), 200);
                }
            }}
        >
            <DialogContent className="sm:max-w-lg">
                <DialogHeader>
                    <DialogTitle>{noteId ? "Edit" : "Create"} note</DialogTitle>
                </DialogHeader>
                <DialogDescription className="hidden">
                    {noteId ? "Edit" : "Create"} note
                </DialogDescription>
                <form onSubmit={noteMutation.mutate}>
                    <NotesFormInputs />
                    <DialogFooter className="sm:justify-start">
                        <DialogClose asChild>
                            <Button type="button" variant="secondary">
                                Close
                            </Button>
                        </DialogClose>
                        <DialogClose asChild>
                            <Button type="submit">Save</Button>
                        </DialogClose>
                    </DialogFooter>
                </form>
            </DialogContent>
        </Dialog>
    );
}

export default NotesDialog;

// src/lib/components/notes/notes-dialog.svelte
<script lang="ts">
    import { route } from "$lib/router";
    import { mutateNote } from "$lib/util/mutate-utils/mutate-note";
    import { queryClient } from "$lib/util/query-utils/query-client";
    import { toast } from "svelte-sonner";
    import * as Dialog from "$lib/components/ui/dialog/index.js";
    import { Button } from "../ui/button";
    import NotesFormInputs from "./notes-form-inputs.svelte";
    import { createMutation } from "@tanstack/svelte-query";

    const params = $derived($route.split("/").slice(1));
    const noteId = $derived(params.find((param) => !isNaN(+param.toString())));
    const isNew = $derived($route.includes("new"));
    let dialogOpen = $state(false);
    let noteMutation = createMutation({
        mutationKey: ["note", () => (noteId ? "edit" : "add")],
        mutationFn: async (formData: FormData) => {
            await mutateNote(formData, noteId, noteId ? "PATCH" : "POST");
        },
        onError: (error: Error, variables) => {
            toast.error(error.message, {
                description: "Error saving note",
                action: {
                    label: "Try again",
                    onClick: () => $noteMutation.mutate(variables),
                },
            });
        },
        onSettled: () => {
            queryClient.invalidateQueries({ queryKey: ["notes"] });
        },
    });
    $effect(() => {
        dialogOpen = !!noteId || isNew;
        noteMutation = createMutation({
            mutationKey: ["note", noteId ? "edit" : "add"],
            mutationFn: async (formData: FormData) => {
                await mutateNote(formData, noteId, noteId ? "PATCH" : "POST");
            },
            onError: (error: Error, variables) => {
                toast.error(error.message, {
                    description: "Error saving note",
                    action: {
                        label: "Try again",
                        onClick: () => $noteMutation.mutate(variables),
                    },
                });
            },
            onSettled: () => {
                queryClient.invalidateQueries({ queryKey: ["notes"] });
            },
        });
    });
</script>

<Dialog.Root
    open={dialogOpen}
    onOpenChange={(isOpen) => {
        dialogOpen = isOpen;
        if (!isOpen) {
            setTimeout(() => window.history.back(), 200);
        }
    }}
>
    <Dialog.Content class="sm:max-w-lg">
        <Dialog.Header>
            <Dialog.Title>{noteId ? "Edit" : "Create"} note</Dialog.Title>
        </Dialog.Header>
        <Dialog.Description class="hidden">
            {noteId ? "Edit" : "Create"} note
        </Dialog.Description>
        <form
            onsubmit={(e) => {
                e.preventDefault();
                const formData = new FormData(e.target as HTMLFormElement);
                $noteMutation.mutate(formData);
            }}
        >
            <NotesFormInputs />
            <Dialog.Footer class="sm:justify-start">
                <Dialog.Close>
                    {#snippet child({ props })}
                        <Button type="button" variant="secondary" {...props}
                            >Close</Button
                        >
                    {/snippet}
                </Dialog.Close>
                <Dialog.Close>
                    {#snippet child({ props })}
                        <Button {...props} type="submit">Save</Button>
                    {/snippet}
                </Dialog.Close>
            </Dialog.Footer>
        </form>
    </Dialog.Content>
</Dialog.Root>
